### PR TITLE
Use gethostname on Windows

### PR DESCRIPTION
**Pull request by Jake-Shadle**
The Windows implementation was using `GetComputerName` even though
`gethostname` is available on Windows, so I updated to the latest winapi
instead of winutil.

Also added CI.

### CODE REVIEW

**Comment by Jake-Shadle** [comment]
This should also fix #3 as it removes the `winutil` dependency and therefore the loose dependency on `winapi` in favor of a more strict one.

**Comment by fengcen** [comment]
Thanks.

I found that these changes will cause performance problems:

Before:
before

After:
after

So I think there is no need to change. Thanks anyway.

**Comment by Jake-Shadle** [comment]
Yah, I didn't run the benchmark, my bad!

I've updated to use `GetComputerNameExA` instead, so I get
image

Which is roughly 5 times as expensive as the previous version on my machine, but should be more accurate as the function winutil is calling is capped at 16 characters (including null terminator) while this one can represent the full hostname.

**Comment by swsnr** [comment]
I‘d like to see this change applied; GetComputerName returns the truncated netbios name which is not necessarily the same as the system received from DHCP for DNS.

I’d use ComputerNamePhysicalDnsHostname though because it probably does less DNS calls, and perhaps also GetComputerNameExW instead of *A because DNS can contain Unicode probably.

At least that’s what Python does in [socket.gethostname](https://github.com/python/cpython/blob/master/Modules/socketmodule.c) and I believe Python receive a good deal of real world testing here.

**Comment by fengcen** [comment]
Sorry guys. I have no time and interest in Rust right now. This project is going to **Abandoned** status.

**Comment by Jake-Shadle** [comment]
@fengcen in that case I wouldn't mind taking over ownership of this crate since I work in rust full time now. :slightly_smiling_face:

**Comment by swsnr** [comment]
@Jake-Shadle I did [gethostname.rs](https://github.com/lunaryorn/gethostname.rs) meanwhile.

**Comment by Jake-Shadle** [comment]
Cool, guess we can just use that instead, thanks!

**Pull request closed without merging**
